before_script:
  - mysql -uroot -e "create database hoge"
  - mysql -uroot -e "create table tokyo"
  - mysql -uroot -e "create table saitama"
  - mysql -uroot -e "create table osaka"
script:
  - php -f show_tables.php
