before_script:
  - mysql -uroot -e "create database hoge"
  - mysql -uroot -e "use hoge; create table tokyo"
  - mysql -uroot -e "use hoge; create table saitama"
  - mysql -uroot -e "use hoge; create table osaka"
script:
  - php -f show_tables.php
