language: php
php:
  - 5.3
before_install:
  - git clone https://github.com/abraham/twitteroauth.git
before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
  - git clone --depth=1 git://github.com/zenovich/runkit.git
  - cd runkit
  - phpize
  - ./configure
  - make
  - make install
  - phpenv config-add travis.php.ini
script:
  - phpunit
after_script:
  - php vendor/bin/coveralls -v
