name: Deploy
on: [push]
jobs:
  run-tests:
    name: Dummy test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v1
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Install ack-grep
      run: |
        sudo apt-get install ack-grep

    - name: Install ack
      run: |
        sudo apt-get install ack

    - name: Put test files
      run: |
        echo "test" >> sample.txt

    # - name: Run grep
    #   run: |
    #     pwd
    #     ls -la
    #     grep hello dummy_1.txt

    - name: Run ack F
      run: |
        ack -s --nopager --nofilter hello

    - name: Run ack B
      run: |
        ack -s --filter hello

    - name: Run ack A
      run: |
        ANSI_COLORS_DISABLED=1 ack hello

    - name: Run ack 0
      run: |
        ack -s --nofilter hello

    - name: Run ack 1
      run: |
        pwd
        ls -la
        ack --nofilter hello

    - name: Run ack 2
      run: |
        pwd
        ls -la
        ack --nofilter test
