name: Deploy
on: [push]
jobs:
  run-tests:
    name: Dummy test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Install ack command
      run: |
        sudo apt-get install ack-grep

    - name: Put test files
      run: |
        echo "test" >> sample.txt

    - name: Run ack
      run: |
        pwd
        ls -la
        grep test dummy_1.txt

    - name: Run ack
      run: |
        pwd
        ls -la
        ack test
